## Numpy Broadcasting

**Broadcasting** - это набор правил, который позволяет функциям и методам производить корректные вычисления при работе с многомерными массивами и массивами разной длины.

Для успешого выполнения операций необходимо привести массивы к одной размерности. 


In [1]:
import numpy as np

Главное правило *broadcasting*: если массивы имеют разную размерность, то к массивам меньшей длины будет применяться операция повторения, до тех пор, пока размерности массивов не совпадут.

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a + 100   # 100 -> [100, 100, 100, 100, 100]

array([100, 101, 102, 103, 104])

Это эквивалентно следующей записи:

In [4]:
b = np.full(a.shape, 100)
a + b

array([100, 101, 102, 103, 104])

Аналогичное правило действует для многомерных массивов.

In [5]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
a - 7

array([[-7, -6, -5, -4],
       [-3, -2, -1,  0]])

Математические операции с векторами и массивами подчиняется тем же правилам

In [7]:
a = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b = np.array([5, 5, 5])
b

array([5, 5, 5])

In [9]:
a+b   # b is extending: [[5, 5, 3], [5, 5, 5]]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

Broacasting позволяет изменять размер массивов. Например, сложение вектора-строки и вектора-столбца порождает квадратную матрицу:

In [10]:
a = np.arange(3)
a

array([0, 1, 2])

In [11]:
b = np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [12]:
a + b    # Square matrix NxN

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
a * b    # Square matrix NxN

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

### Broadcasting

![Broadcasting Rules](broadcasting.png)

Прозрачные области - это "растянутые" части массивов. В процессе broadcasting НЕ создается новый массив, а также не затрачивается дополнительная память на расширение массивов! 

## Broadcasting Rules
NumPy следует строгому набору правил для определения соответствия между двумя массивами. 

1. Если два массива отличаются по количеству измерений, то массив меньшего размера "дополняется" до большего массива.
2. Если массивы не совпадают ни в одном измерении, массив с размерностью 1 в одном из измерений " растягивается" до массива большего размера.
3. Если размерности массивов не совпадают и ни одно из измерений не равно 1, возникает ошибка.

Таким образом, массивы меньшего размера "дополняются" до большего, если это возможно. В противном случае broadcasting невозможен и возникает ошибка. 

Итоговый массив будет содержать максимальный размер по каждому из измерений.

In [14]:
a1 = np.ones(shape=(1, 2, 3))
a2 = np.ones(shape=(3, 1, 1))
print(a1.shape)
print(a2.shape)

(1, 2, 3)
(3, 1, 1)


In [15]:
a3 = a1 + a2
a3

array([[[2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.]]])

In [16]:
a3.shape    # shapes: (1, 2, 3) + (3, 1, 1)

(3, 2, 3)

## Логические операции

Ещё раз вернемся к логическим операциям с массивами Numpy.

Numpy позволяет выбирать элементы массива с помощью булевых операций in-place. Благодаря broadcasting можно применять операторы к различным элементам массива.

In [17]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
x[x < 6]   # Print elements < 6

array([0, 1, 2, 3, 4, 5])

In [19]:
x < 6      # Print boolean values for this condition

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [20]:
x != 6     # Find not equal values into 'x'

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [21]:
x == 6     # Find equal value into 'x'

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [22]:
(x % 2) == 0   # Find only even numbers

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [23]:
(x == 6) | (x == 7) | (x == 8)    # Find equal values

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True, False, False, False]])

In [24]:
y = (3 < x) & (x < 9)       # Find less and more values
y

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [25]:
z = np.array(y, dtype=int)
z

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 0, 0]])

### Математика булевых выражений

С помощью numpy также можно посчитать количество истиных значений в массиве. Например:

In [26]:
np.sum(y)   # Sum of Trues (True == 1)

5

Это эквиваленто подсчету количества единиц в массиве (поскольку boolean это подтип integer):

In [27]:
np.sum(z) == np.sum(y)

True

In [28]:
# Find number of '1' (True values) into 2 < x < 5
x = np.arange(10)
np.sum((x > 2) & (x < 5))

2

In [29]:
# Negative equation
np.sum(~((x > 2) & (x < 5)))

8

### Методы Any & All
Методы и функции *any* и *all* применяются ко всему массиву. Any позволяет узнать является ли хотя бы один элемент массива истиным `True`. All позволяет узнать, являются ли все элементы истиными (отсутсвуют ложные или есть хотя бы один ложный), т.е. `False`.

In [30]:
y

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [31]:
y.any()   # True if one element of the ndarray is True

True

In [32]:
y.all()  # True if all elements of the ndarray are True

False

### Фильтрация с помощью булевых масок

С помощью булевых масок можно производить фильтрацию соответствующих значений в массиве. Например, выбор элементов массива, кратных 5:

In [33]:
w = np.arange(1, 26).reshape(5,5)
w

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
(w % 5) == 0     # Boolean matrix

array([[False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True]])

In [35]:
w[(w % 5) == 0]   # Accept boolean matrix

array([ 5, 10, 15, 20, 25])

Таким образом с помощью фильтрации удалось выбрать элементы кратные 5.

Следующий пример позволяет выбрать все четные числа в заданном диапазоне.

In [36]:
cond = (w >= 3) & (w <= 15)& ((w % 2) == 0)
cond    # Boolean filter

array([[False, False, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [37]:
w[cond]   # Accept filter to ndarray

array([ 4,  6,  8, 10, 12, 14])