## Введение в NumPy

### Основы
Основной объект в Numpy - однородный многомерный массив **ndarray**, представляющий таблицу элементов (как правило, чисел) одного типа, проиндексированных натуральными числами. Размерности массива в Numpy называются осями (**axis**).

Добавление библиотеки в проект:

In [1]:
import numpy as np               # Import numpy 

### Создание массивов NumPy

Ниже представлены различные способы создания массивов. Самый простой - через *list* (список) в Python:

In [2]:
np.array([1, 2, 3, 4, 5, 6, 7], dtype=np.int16)   # Set type = int16

array([1, 2, 3, 4, 5, 6, 7], dtype=int16)

С помощью встроенного метода *arange([start,] stop[, step,], dtype=None)*:

In [3]:
a = np.arange(20, dtype=np.int32).reshape(4, 5)    # Create 2D-array
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int32)

Обратное преобразование массива в список:

In [4]:
a.tolist()    # ndarray to list

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

Массив обладает различными атрибутами (размерность, длина, тип, размер
элементов):

In [5]:
a.dtype      # Type of elements

dtype('int32')

In [6]:
a.shape      # Shape of the array

(4, 5)

In [7]:
a.ndim       # Number of dimensions

2

In [8]:
a.itemsize   # Size of items (for int32 )

4

In [9]:
a.size       # Number of elements in the array

20

In [10]:
type(a)      # Python type method

numpy.ndarray

Numpy позволяет создавать массивы комплексных чисел:

In [11]:
np.array([1, 2, 3, 4], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

### Массивы с начальными значениями
Можно создавать массивы, заполненные нулями, единицами, случайным мусором или пользовательским значением:

In [12]:
np.zeros(5, dtype=int)         # Zeros

array([0, 0, 0, 0, 0])

In [13]:
np.ones((3, 5))                # Ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full(shape=(2,5), fill_value=7, dtype=int)   # Filled with value

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [15]:
np.empty(7)    # Uninitialized array

array([2.0045516e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000])

In [16]:
b = np.empty(5, dtype=int)   # Uninitialized array
b.fill(777)                  # Fill with value
b

array([777, 777, 777, 777, 777])

Для создания массива равномерно распределенных в заданном диапазоне чисел используется метод *linspace*:  

```python
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
```

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Единичная матрица, двумерный массив:

In [18]:
np.eye(5, dtype=int)    # Identity matrix ('I' as eye)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Математические операции с массивами

In [19]:
c = np.arange(8).reshape(2,4)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
c*5     # Multiply

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35]])

In [21]:
c/10    # Divide

array([[0. , 0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6, 0.7]])

In [22]:
c ^ 7   # XOR (note: reversed array)

array([[7, 6, 5, 4],
       [3, 2, 1, 0]])

In [23]:
c.T     # Transpose

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### Различные операции с элементами и срезами

In [24]:
c[1,:]   # Second row, the same as a[1, ...]

array([4, 5, 6, 7])

In [25]:
c[:,1]   # Second column, the same as a[..., 1]

array([1, 5])

In [26]:
c[c>1]   # Boolean for elements

array([2, 3, 4, 5, 6, 7])

In [27]:
c>1      # Boolean for the array

array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
c.flatten()[::-1]    # Flatten and reverse

array([7, 6, 5, 4, 3, 2, 1, 0])

Методы *any* и *all* для булевой проверки элементов в массиве

In [29]:
np.any(c>2)

True

In [30]:
np.all(a>2)

False

### Математические функции и методы

In [31]:
c.sum()      # Sum of elements

28

In [32]:
c.max()      # Max value. The same as max(a)

7

In [33]:
c.min()      # Min value. The same as min(a)

0

In [34]:
np.sqrt(c)   # Square root

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131]])

In [35]:
np.round(np.sin(np.pi/2 * c/c.max()), 2)   # Round, sine, pi

array([[0.  , 0.22, 0.43, 0.62],
       [0.78, 0.9 , 0.97, 1.  ]])

In [36]:
np.prod(c, axis=0)   # Product

array([ 0,  5, 12, 21])

In [37]:
np.cumsum(c)    # Cumulative sum

array([ 0,  1,  3,  6, 10, 15, 21, 28])

### Перебор значений массива

In [38]:
d = np.arange(15).reshape(3,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Проход в цикле по строкам

In [39]:
# Iterating over multidimensional array
for row in d:
    print('Each row * 3: ', 3*row)

Each row * 3:  [ 0  3  6  9 12]
Each row * 3:  [15 18 21 24 27]
Each row * 3:  [30 33 36 39 42]


Проход по всем элементам в цикле с помощью итератора:

In [40]:
# Flat is an iterator! Flatten() returns an array
for el in d.flat:
    if el < 8:
        print(el)

0
1
2
3
4
5
6
7


**Замечание**: *numpy.flat* - одномерный итератор по массиву. *numpy.flatten()* - возвращает одномерную копию массива.

Удобный способ преобразования массива к одномерному виду. Возвращает *view* на объект, а не его копию. Если невозможно вернуть отображение, то создает копию.

In [41]:
d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Метод *ravel* возвращает одномерный массив

In [42]:
d.ravel()
# Return a contiguous flattened array. 
# It is equivalent to reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Метод *flatten* возвращает одномерную копию массива

In [43]:
d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
d.flatten() is d.ravel()

False

### Умножение матриц

In [45]:
np.random.seed(1)
x = np.array([np.random.randint(1, 10) for i in range(9)]).reshape(3,3)
x

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [46]:
y = np.eye(3, dtype=int) * 2
y

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

Оператор * умножает матрицы поэлементно

In [47]:
# Operator * operates elementwise
x*y

array([[12,  0,  0],
       [ 0,  2,  0],
       [ 0,  0,  6]])

Оператор **@** и метод **dot** вычисляет произведение матриц

In [48]:
# Use @ operator for matrix product 
x @ y

array([[12, 18, 12],
       [ 2,  2,  4],
       [16, 14,  6]])

In [49]:
# Use dot function or method
x.dot(y)

array([[12, 18, 12],
       [ 2,  2,  4],
       [16, 14,  6]])

In [50]:
np.dot(x, y)

array([[12, 18, 12],
       [ 2,  2,  4],
       [16, 14,  6]])

### Преобразование матриц

Метод *reshape* возвращает отображение на объект, а метод *resize* изменяет массив на месте (in-place). Методы *transpose* или *.T* возвращают отображение на объект.

In [51]:
z = np.arange(12)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
# View of the array
z.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
# Initial array
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
# In-place change
z.resize(3,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
z.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
z.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Объединение массивов

Методы:
 - *concatenate((a1, a2, ...), axis=0, out=None)*. Объединяет массивы a1, a2 вдоль выбранной оси *axis*.
 - *vstack(tup), hstack(tup)*. Объединяет массивы по вертикали/горизонтали (по строкам / столбцам)
 - *stack(arrays, axis=0, out=None)*. Объединяет массивы по выбранной оси axis.

In [57]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([9, 10, 11, 12])

In [58]:
np.concatenate((a, b), axis=0)  # Concatenate two arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
np.vstack((a, b, c))   # Vertical stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
np.hstack((a, b, c))   # Horizontal stack (flatten!)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
np.stack((a, b, c), axis=0)   # Vertical stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
np.stack((a, b, c), axis=1)   # Horizontal stack (not flatten!)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Разбиение массивов

Методы:
 - *vsplit(ary, indices_or_sections)*, разбивает массивы на подмассивы (векторы) вдоль вертикальной оси (по строкам)
 - *hsplit(ary, indices_or_sections)*. разбивает массивы на подмассивы (векторы) вдоль горизонтальной оси (по столбцам)
 - *split(ary, indices_or_sections, axis=0)*. разбивает массивы на подмассивы вдоль выбранной оси

Все перечисленные методы возвращают *list* массивов *ndarray*.

In [63]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [64]:
np.vsplit(x, 4)   # Vertical split

[array([[0., 1., 2., 3.]]),
 array([[4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]])]

In [65]:
np.hsplit(x, 2)   # Horizontal split

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [66]:
np.split(x, 2, axis=0)   # Samse as vertical split

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [67]:
np.split(x, 2, axis=1)   # Samse as horizontal split

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]