## Numpy Copies and Views

При работе с массивами зачастую создаются не новые объекты, а их отображения или ссылки на тот же объект.

### Присваивание без копирования
Пример с присваиванием значения по индексу массива:

In [1]:
import numpy as np

In [2]:
# Create an array
a = np.arange(6)
b = a    # no new object is created
a        # print a

array([0, 1, 2, 3, 4, 5])

In [3]:
a[0] = 9   # change one element
b          # b[0] has been changed too!

array([9, 1, 2, 3, 4, 5])

В отличие от С++ в Python прямое присваивание массивов не создает новую копию! Вместо этого создается новая ссылка на объект *nparray* и значение *refcnt* увеличивается на 1.

In [4]:
a is b

True

In [5]:
np.all(a == b)

True

Идентификаторы объектов также равны!

In [6]:
id(a) == id(b)

True

Python передает изменяемые объекты в качестве *ссылок*, поэтому вызовы функций не создают локальных копий объектов.

In [7]:
print(id(a))

def calc(x):
    print(id(x))

calc(a)   # id is a unique identifier of an object

140487729739136
140487729739136


### Отображение (представление) или поверхностная копия

Разные объекты могут совместно использовать одни и те же данные. Метод **view** создает новый массив (объект), который указывает на те же данные.

In [8]:
c = a.view()
c

array([9, 1, 2, 3, 4, 5])

В связи с этим, элементы массивов равны друг другу, но новый массив указывает на другое место

In [9]:
np.all(b == a)

True

In [10]:
c is a

False

In [11]:
id(a) == id(c)

False

Атрибуты *base* и *flags.owndata* нового массива:

In [12]:
c.base is a  # c is a view of the data owned by a

True

In [13]:
c.flags.owndata

False

При изменении **размерности** массива, оригинальный массив не меняется:

In [14]:
c.shape = (2,3)  # a's shape doesn't change
c

array([[9, 1, 2],
       [3, 4, 5]])

In [15]:
a

array([9, 1, 2, 3, 4, 5])

При изменении **значения** массива, оригинальный массив изменяется:

In [16]:
c[0,0] = 7

In [17]:
a

array([7, 1, 2, 3, 4, 5])

Замечание: метод **reshape** возвращает view, а если это невозможно - создает copy массива!

In [18]:
a.reshape(3,2)   # view

array([[7, 1],
       [2, 3],
       [4, 5]])

In [19]:
a   # original array

array([7, 1, 2, 3, 4, 5])

Таблица методов и возвращаемые значения:

| N  | method        | return | description |
|---:| -------------:| ---------------------------------------------:|---------------------------------:|
| 1  | transpose     | view                                          | транспонирование матрицы         |
| 2  | reshape       | view, otherwise - copy                        | изменение размерности массива    |
| 3  | split         | list of subarrays (same as hsplit, vsplit)    | разбиение массива на подмассивы  |
| 4  | stack         | new array (same as hstack, vstack)            | слияние массивов                 |
| 5  | repeat        | new array                                     | повторение массива               |
| 6  | tile          | new array                                     | повторение массива               |
| 7  | ravel         | new array                                     | выравнивание массива вдоль оси   |
| 8  | concatenate   | new array                                     | объединение массивов             |
| 9  | resize        | new array, in-place change an old array       | изменение размерности массива    |
| 10 | flatten       | copy of the array                             | выравнивание массива             |
| 11 | flat          | A 1-D iterator over the array                 | итератор по одномерному массиву  |

### Срезы массива 
Срезы возвращают отображение (view) на массив, а не его копию!

In [20]:
s = a[:3]   # get three elements of 'a'
s[:] = 0    # set all elements = 0
s

array([0, 0, 0])

In [21]:
a   # 'a' has been changed

array([0, 0, 0, 3, 4, 5])

In [22]:
a[-3:-1] = 1
a

array([0, 0, 0, 1, 1, 5])

### Копия (deep copy)

Для создания полноценной копии массива используется одноименный метод **copy**

In [23]:
a   # Old array

array([0, 0, 0, 1, 1, 5])

In [24]:
b = a.copy()   # Deep copy
b

array([0, 0, 0, 1, 1, 5])

In [25]:
a is b   # Objects aren't equal

False

In [26]:
b.flags.owndata    # New array with own data

True

In [27]:
b[:] = 9
b

array([9, 9, 9, 9, 9, 9])

In [28]:
a

array([0, 0, 0, 1, 1, 5])